### ISSUE TITLE
Some returned values are `undefined`

### ISSUE THREAD

**Issue by lapin-b** [stephenpoole/op.gg-api#13]
Hi,
I'm writing an app for a Discord server but some returned values are undefined. I leave [a link to my PrivateBin](https://paste.l4p1n-pi.tk/?67ff55bda149a5f3#2Wk2pKfkJO/QvWUURby6T+yl+NEMeo+ANqROFWnn9yM=) with the returned response.

As you can see, some values are `NaN` or `undefined`.

## Reproducing
1. Require the library like so:
```javascript
const opgg = new (require('op.gg-api/client.js'))({
    api_key: process.env.LOLAPIKEY
});
```
2. Then, fetch the API with the library with a specific username
```javascript
let summoner_summary = await opgg.Summary('euw', requestedSummoner)
// Where requestedSummoner is... the requested LoL summoner, i.e. xxpafadelcraftxx
```
3. Console.log everything and you should see that some values are `undefined` or `NaN` which can be a bit annoying if I want to integrate the API in my application...

Am I doing something wrong or it's a bug on the library side ?

**Comment by stephenpoole** [comment]
It is certainly the fault of the library. Unfortunately, this is the nature of scraping. If the DOM structure is changed after implementation, then whatever query will no longer return the expected result. Let me know if you find anything else.
