### ISSUE TITLE
Feature request - match_id and start_time/end_time for matches on summoner

### ISSUE THREAD

**Issue by freakpants** [stephenpoole/op.gg-api#2]
I'd love to see match_id and start/end of game for every game when pulling a summoner so that I can avoid entering the same game twice and sort them by when they happened :)

and thanks for fixing the bug :+1:

**Comment by freakpants** [comment]
Matchid as in the matchid for the game, not for spectating

**Comment by stephenpoole** [comment]
That information isn't available on the summoner page. You'll need to make multiple calls and combine the results.

**Comment by freakpants** [comment]
![game-id](https://cloud.githubusercontent.com/assets/12885929/8750759/97413bac-2ca9-11e5-8da4-ecaf17cab98e.PNG)

i should have referred to game_id, my bad. sadly its inside the class name, but its there.

**Comment by freakpants** [comment]
<span class="_timeago tip" data-datetime="1436898547" data-type="" original-title="14. Jul. 2015 20:29 Uhr">vor 3 Tagen</span>

<span class="gameLength">
				24m 32s
			</span>

Contains the timestamp of the game, and the duration. not sure if its the beginning or end of the game, but one will of course imply the other :)

**Comment by stephenpoole** [comment]
Good catch. Added these.
