### ISSUE TITLE
Feature request - Force op.gg to update the summoner

### ISSUE THREAD

**Issue by freakpants** [stephenpoole/op.gg-api#4]
Is there a way to force op.gg to update the summoner before requesting the data?

im building a match  ticker that tracks tournament matches (http://www.gamerbase.ch/poros-matchticker/) and sometimes (mostly unless the players do it) i have to manually refresh the summoners for the match ticker to pick up the matches.

**Comment by stephenpoole** [comment]
It is possible, but it requires 3 calls. One to /summoner to get the summoner ID, a second to /refresh (which I can implement), and a third to get the refreshed data. This could be avoided if you cached summoner ID's, though.

**Comment by freakpants** [comment]
I already save summonerIds locally, as it is more reliable than summoner names which can be chagned. Would love to see an implementation of a refresh call. :)

**Comment by freakpants** [comment]
I see you already implemented it! That was fast! I'm going to have to donate some money to you at some point :D Thanks!
