### ISSUE TITLE
Requests don't return data anymore

### ISSUE THREAD

**Issue by freakpants** [stephenpoole/op.gg-api#8]
Well formed requests only return {"status":"ok","data":false}.

This happens with all requests for Summoners on EUW currently.

**Comment by mrmans0n** [comment]
Any luck with this?

**Comment by DaCaemboe** [comment]
Has this issue been resolved? Just started using it and even the example returns this error

**Comment by stephenpoole** [comment]
This is an issue that affects all endpoints. op.gg have since updated their site, so the code that parses the pages needs to be updated. I'm currently in the process of rewriting.
